### ISSUE TITLE
ModuleNotFoundError when run

### ISSUE THREAD

**Issue by Youtheone1** [Reverend-Toady/Spotify-Downloader#2]
when the program is run the folloing error is shown:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from SpotifyDownloader.YoutubeDownloader import downloader
  File "C:\Users\feren\Downloads\Spotify-Downloader-main\SpotifyDownloader\YoutubeDownloader.py", line 1, in <module>
    from SpotifyDownloader.SpotifyWebAPI import get_playlists, get_access_token
  File "C:\Users\feren\Downloads\Spotify-Downloader-main\SpotifyDownloader\SpotifyWebAPI.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

used the command:  py main.py -u https://open.spotify.com/playlist/urlhere -p C:\Users\admin\Downloads\

**Comment by Reverend-Toady** [comment]
Hey there, did you run `$pip install -r requirements.txt` before executing the code?

**Comment by Youtheone1** [comment]
> 
> 
> Hey there, did you run `$pip install -r requirements.txt` before executing the code?

I didn't, this fixed thank you vaery much. :)
